# Generated by Django 3.2.4 on 2021-06-13 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название предмета')),
            ],
            options={
                'verbose_name': 'ЕГЭ',
                'verbose_name_plural': 'ЕГЭ',
            },
        ),
        migrations.CreateModel(
            name='Kurses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название профессии')),
                ('url', models.CharField(max_length=1000, verbose_name='Ссылка на подробное опичание профессии')),
                ('img', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Фотография')),
                ('level', models.CharField(blank=True, max_length=255, null=True, verbose_name='Уровень подготовки')),
                ('vid', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вид подготовки')),
                ('category', models.CharField(blank=True, max_length=255, null=True, verbose_name='Категория подготовки')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название профессии')),
                ('url', models.CharField(max_length=1000, verbose_name='Ссылка на подробное опичание профессии')),
            ],
            options={
                'verbose_name': 'Профессия',
                'verbose_name_plural': 'Профессии',
            },
        ),
        migrations.CreateModel(
            name='Spec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название специальности')),
                ('url', models.CharField(max_length=1000, verbose_name='Ссылка на подробное опичание специальности')),
                ('price', models.CharField(blank=True, max_length=10, null=True, verbose_name='Цена за обучение')),
                ('budzhet', models.CharField(blank=True, max_length=3, null=True, verbose_name='Минимальный балл для поступления на бюджет')),
                ('budzhet_mest', models.CharField(blank=True, max_length=4, null=True, verbose_name='Количество свободных мест на бюджет')),
                ('platno', models.CharField(blank=True, max_length=3, null=True, verbose_name='Минимальный балл для поступления на платное')),
                ('platno_mest', models.CharField(blank=True, max_length=4, null=True, verbose_name='Количество свободных мест на платное')),
                ('ege', models.ManyToManyField(to='devmodip.Ege')),
                ('prof', models.ManyToManyField(to='devmodip.Profession')),
            ],
            options={
                'verbose_name': 'Специальноть',
                'verbose_name_plural': 'Специальности',
            },
        ),
        migrations.CreateModel(
            name='Vuz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название вуза')),
                ('obshaga', models.BooleanField(verbose_name='Общежитие')),
                ('gos', models.BooleanField(verbose_name='Государственный')),
                ('voen', models.BooleanField(verbose_name='Военная кафедра')),
                ('accred', models.BooleanField(verbose_name='Акредитован/Лицензирован')),
                ('spec', models.ManyToManyField(to='devmodip.Spec')),
            ],
            options={
                'verbose_name': 'ВУЗ',
                'verbose_name_plural': 'ВУЗы',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurses', models.ManyToManyField(to='devmodip.Kurses')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prof', models.ManyToManyField(to='devmodip.Profession')),
                ('spec', models.ManyToManyField(to='devmodip.Spec')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
            },
        ),
        migrations.CreateModel(
            name='PersonData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobbi', models.CharField(max_length=255, verbose_name='Хобби')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prof_predmet', models.ManyToManyField(to='devmodip.Ege')),
                ('want_prof', models.ManyToManyField(to='devmodip.Profession')),
                ('want_spec', models.ManyToManyField(to='devmodip.Spec')),
            ],
            options={
                'verbose_name': 'Личные данные',
                'verbose_name_plural': 'Личные данные',
            },
        ),
        migrations.CreateModel(
            name='LearnPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurses', models.ManyToManyField(to='devmodip.Kurses')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prof', models.ManyToManyField(to='devmodip.Profession')),
                ('spec', models.ManyToManyField(to='devmodip.Spec')),
            ],
            options={
                'verbose_name': 'Учебный план',
                'verbose_name_plural': 'Учебные планы',
            },
        ),
    ]
